-- AlterTable
ALTER TABLE "Route" ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "amount_rates" SET DEFAULT 0,
ALTER COLUMN "rate" SET DEFAULT 0,
ALTER COLUMN "difficulty" SET DEFAULT 0,
ALTER COLUMN "popularity" SET DEFAULT 0;
